=== rsvives/recuperacion2Evaluacion/Tema-4/index.dtd
<!ATTLIST tournament id ID #REQUIRED>
<!ELEMENT asociation (tournament) >
<!ELEMENT tournament (year, information)>
<!ELEMENT information (identify, identify2, name, years, country, serie)>
<!ELEMENT year  (#PCDATA)>
<!ELEMENT identify (#PCDATA)>
<!ELEMENT identify2 (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT years (#PCDATA)>
<!ELEMENT country (#PCDATA)>
<!ELEMENT serie (#PCDATA)>

=== rsvives/recuperacion2Evaluacion/Tema-4/index.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE asociation SYSTEM "./index.dtd">
<asociation>
    <tournament id="hola">
        <year>1994</year>
        <information>
            <identify>1</identify>
            <identify2>2</identify2>
            <name>Nicolas</name>
            <years>18</years>
            <country>Asturias</country>
            <serie>1</serie>
        </information>
    </tournament>
</asociation>
